models/Entry.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "entry".
 *
 * @property integer $id
 * @property string $title
 * @property string $text
 * @property integer $status
 */
class Entry extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'entry';
    }
    
    public static function statusName($st)
    {
	    switch ($st)
    	{
    		case 1:
    			return 'In work';
    			break;
    		case 2:
    			return 'Done';
    			break;
    		case 0:
    			return 'Reject';
    			break;
    		default:
    			return "";
    	}
    }
    
    public function getStatus()
    {
    	return Entry::statusName($this->status);
	}
	
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
			[['status', 'title', 'text'], 'required'],
            [['status'], 'integer'],
            [['title'], 'string', 'max' => 45],
            [['text'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'text' => 'Text',
            'status' => 'Status',
        ];
    }
}

controllers/EntryController.php
<?php

namespace app\controllers;
use Yii;
use app\models\Entry;
use \yii\base\HttpException;

class EntryController extends \yii\web\Controller
{
    public function actionIndex()
	{
	    $post = new Entry;
	    $data = $post->find()->all();
	    echo $this->render('index', array(
	        'data' => $data
	    ));
	}
	
	public function actionRead($id=NULL)
	{
	    if ($id === NULL)
            throw new HttpException(404, 'Not Found');
 
        $entry = Entry::find($id);
 
        if ($entry === NULL)
            throw new HttpException(404, 'Document Does Not Exist');
 
        echo $this->render('read', array(
            'entry' => $entry
        ));
	}
	
	public function actionDelete($id=NULL)
	{
		if ($id === NULL)
	    {
	        Yii::$app->session->setFlash('EntryDeletedError');
	        Yii::$app->getResponse()->redirect(array('entry/index'));
	    }
	 
	    $entry = Entry::find($id);
	 
	 
	    if ($entry === NULL)
	    {
	        Yii::$app->session->setFlash('EntryDeletedError');
	        Yii::$app->getResponse()->redirect(array('entry/index'));
	    }
	 
	    $entry->delete();
	 
	    Yii::$app->session->setFlash('EntryDeleted');
	    Yii::$app->getResponse()->redirect(array('entry/index'));
	}
	
	public function actionCreate()
	{
	    $model = new Entry;
	    if (isset($_POST['Entry']))
	    {
			$model->attributes = $_POST['Entry'];
	 
	        if ($model->save())
	        {
	        	if (!isset($_POST['ajax'])) Yii::$app->getResponse()->redirect(array('entry/read', 'id' => $model->id));
		        return;
		    }
	    }
		
	    echo $this->render('create', array(
	        'model' => $model
	    ));
	}
	
	public function actionUpdate($id=NULL)
	{
	    if ($id === NULL)
	        throw new HttpException(404, 'Not Found');
	 
	    $model = Entry::find($id);
	 
	    if ($model === NULL)
	        throw new HttpException(404, 'Entry Does Not Exist');
	 
	    if (isset($_POST['Entry']))
	    {
	        $model->attributes = $_POST['Entry'];
	 
	        if ($model->save())
	        {
	            Yii::$app->getResponse()->redirect(array('entry/read', 'id' => $model->id));
	            return;
	        }
	    }
	 
	    echo $this->render('update', array(
	        'model' => $model
	    ));
	}
}

views/entry/create.php
<?php use yii\helpers\Html;
 	  use app\models\Entry; ?>
 
<?php $form = \yii\widgets\ActiveForm::begin(array(
    'options' => array('class' => 'form-horizontal'),
)); ?>
    <?php echo $form->field($model, 'title')->textInput(array('class' => 'span8 input-sm')); ?>
    <?php echo $form->field($model, 'text')->textArea(array('class' => 'span8 input-sm', 'rows'=>3)); ?>
    <?php echo $form->field($model, 'status')->dropDownList(array(
    	1 => Entry::statusName(1),
    	2 => Entry::statusName(2),
    	0 => Entry::statusName(0),
    ), array('class' => 'form-control input-sm')); ?>
    <div class="form-actions">
        <?php echo Html::submitButton('Create', array('class' => 'btn btn-primary')); ?>
    </div>
<?php \yii\widgets\ActiveForm::end(); ?>

views/entry/index.php
<?php use yii\helpers\Html; ?>
 
<?php echo Html::a('Create New Entry', array('entry/create'), array('class' => 'btn btn-primary pull-right')); ?>
<div class="clearfix"></div>
<hr />
<?php if(Yii::$app->session->hasFlash('EntryDeletedError')): ?>
	<div class="alert alert-error">
	    There was an error deleting your TODO entry!
	</div>
	<?php endif; ?>
	 
	<?php if(Yii::$app->session->hasFlash('EntryDeleted')): ?>
	<div class="alert alert-success">
	    Your TODO entry has successfully been deleted!
	</div>
<?php endif; ?>
<table class="table table-striped table-hover">
    <tr>
        <td>#</td>
        <td>Title</td>
        <td>Text</td>
        <td>Status</td>
        <td>Options</td>
    </tr>
    <?php foreach ($data as $entry): ?>
        <tr>
            <td>
                <?php echo Html::a($entry->id, array('entry/read', 'id'=>$entry->id)); ?>
            </td>
            <td><?php echo Html::a($entry->title, array('entry/read', 'id'=>$entry->id)); ?></td>
            <td><?php echo $entry->text; ?></td>
            <td><?php echo $entry->getStatus(); ?></td>
            <td>
                <?php echo Html::a('Edit', array('entry/update', 'id'=>$entry->id), array('class'=>'icon icon-edit')); ?>
                <?php echo Html::a('Del', array('entry/delete', 'id'=>$entry->id), array('class'=>'icon icon-trash', 'onclick' => "return confirm('Вы точно хотите удалить сообщение?')")); ?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

views/entry/read.php
<?php use yii\helpers\Html; ?>
<div class="pull-right btn-group">
	<?php echo Html::a('All', array('entry/index'), array('class' => 'btn btn-info')); ?>
    <?php echo Html::a('Update', array('entry/update', 'id' => $entry->id), array('class' => 'btn btn-primary')); ?>
    <?php echo Html::a('Delete', array('entry/delete', 'id' => $entry->id), array('class' => 'btn btn-danger', 'onclick' => "return confirm('Вы точно хотите удалить сообщение?')")); ?>
</div>
 
<h1><?php echo $entry->title; ?></h1>
<p><?php echo $entry->text; ?></p>
<hr />
<p>Status: <?php echo $entry->getStatus(); ?></p>

views/entry/update.php
<?php use yii\helpers\Html;
 	  use app\models\Entry; ?>
 
<?php $form = \yii\widgets\ActiveForm::begin(array(
    'options' => array('class' => 'form-horizontal'),
)); ?>
    <?php echo $form->field($model, 'title')->textInput(array('class' => 'span8 input-sm')); ?>
    <?php echo $form->field($model, 'text')->textArea(array('class' => 'span8 input-sm', 'rows'=>3)); ?>
    <?php echo $form->field($model, 'status')->dropDownList(array(
    	1 => Entry::statusName(1),
    	2 => Entry::statusName(2),
    	0 => Entry::statusName(0),
    ), array('class' => 'form-control input-sm')); ?>
    <div class="form-actions">
        <?php echo Html::submitButton('Update', array('class' => 'btn btn-primary')); ?>
    </div>
<?php \yii\widgets\ActiveForm::end(); ?>